language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eCmf2Oy06AriAKNvWYVh1dPiZ+sFmm5PVkTqr3JqoOVv/uM4mQYUD1rhwvf0lxlhpjgltq0egn7kWBipmMKbEVy0f5p8OQkhoIBXXJ/MQsCumqBNboW1ktHC5waoU2WdtMShiTryRpZ1UoAoQ3j2ze5MwJZrj++HuEZXjF7VuaLvCkT0oqfV75fob4jFVTrtRPF43jr6JWRVT3olZcpCZfpKP8QiApr1tjWZ2DwnkGrlDeI/5UlRXVP3cviCqvSfxLswNiC0+rs37MImWLGwy8GOVAa21eqzONvTmTHgojHRomwx5qbMjdhBLAlXQnleWr38261Q2idZ7DPZhe0vvUgSp8R9vhOoRhUr0sduZtNTAQun5ROQd6o9sUjRiHVEJu10FDcsOBM68DeoKoUexSp06Mb0DjN8kzi1KhxGQJp0iwNJtDMVvkb9MwZVOFydVHaCsutOcaF8NPLfI9/PFmN7rxAeZd+d1sH1bV4iKboUsH+hAK4S0po9avQSisDYFKasOcqQMR7g5BGV7FsgKqoGN4DnmOV/feCcbQ7tWNrJA0wn5bVpURELC6ZiWUrEQAm6Peke38BwUFgjHkohtUKlmXvxEYUxWninCa8wrVaBNP3JmJcGNWPYgeIn7AcCx3wxzGVy+TmSujBCav1wK2Hz50h8DtDuqEng2yYSOvs=
  file:
    - 'unist-util-remove-position.js'
    - 'unist-util-remove-position.min.js'
  on:
    tags: true
