language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FX7DMU5oxzHrjhOGZlXq+C33HQzkgPU83T6bfcs5Ehe0XyHrwepoz+1LztVgRYSNaosls9oCi8e94S8O+cUlnUAPXKNrPGIq3C+IBDChYmj1+1bqlyPpA2DNGoXSefR1EHEzFo3RKGNuDmh7+2I1y1MI92pbQd4vfoyBQOUX5APCNMNyaGaXtIODB7wI+NAfwagCUspNxrCvRQ3q4Phwqi9LAchakIbUVEbc3FD7PR/IKf/7So8PawH2Ywe66xdwp/ca4TEE9ytHIEemQYV2fdMfbByDasrzDVQEbXbPxAFGHo0ARaveHw1oYIl+aTZwXZxQi4npdt/Ag+N3m7KBxmsSh+i8MSJoMmPJCbnRhZtLqVyJmAO0MGv5aGTI0vDQ89+TCNp23wPl1wuWMrlRFCS0e+F0sUqKLaSpYEYMNS5FysV1Axv0U0NFaNynehRQG1LegTUh/+GBXJ61QlRyKS+apyNVgVFQy9DZFgI+nXKguh9SwI8uu7oSKB1CmDVEUxp89DL6ieF2W/KbZZHN/AqZ0uKrlSg1YtVQkebcInSQEmuG676gkIN67cYPmqQuT1QZkEQvS5jNoIoBy2FddrD5FHkdroizjdWVP+KpGfKaIvOA4lUmmwop+51ki/j9fxXRX1sle55QUgdOEkcSdq0H+0i7YShcz+fsDP2TBO4=
  file:
    - "unist-util-remove-position.js"
    - "unist-util-remove-position.min.js"
  on:
    tags: true
